AllCops:
  Exclude:
    - 'db/seeds.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
